
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka

# 使用默认的Spring Boot配置的HTTP Basic安全性
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456
