server:
  port: 8762

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://root:123456@localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql : true

  application:
    name: springcloud-user-service


