eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://root:123456@localhost:8761/eureka
spring:
  application:
    name: springcloud-user-web
    instance:
      instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
      prefer-ip-address: true

server:
  port: 8763




